/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SvmRouteImport } from './routes/svm'
import { Route as PortafolioRouteImport } from './routes/portafolio'
import { Route as NlpRouteImport } from './routes/nlp'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as LstmRouteImport } from './routes/lstm'
import { Route as EstrategiasRouteImport } from './routes/estrategias'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BrokerRouteImport } from './routes/broker'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const SvmRoute = SvmRouteImport.update({
  id: '/svm',
  path: '/svm',
  getParentRoute: () => rootRouteImport,
} as any)
const PortafolioRoute = PortafolioRouteImport.update({
  id: '/portafolio',
  path: '/portafolio',
  getParentRoute: () => rootRouteImport,
} as any)
const NlpRoute = NlpRouteImport.update({
  id: '/nlp',
  path: '/nlp',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const LstmRoute = LstmRouteImport.update({
  id: '/lstm',
  path: '/lstm',
  getParentRoute: () => rootRouteImport,
} as any)
const EstrategiasRoute = EstrategiasRouteImport.update({
  id: '/estrategias',
  path: '/estrategias',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerRoute = BrokerRouteImport.update({
  id: '/broker',
  path: '/broker',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/broker': typeof BrokerRoute
  '/dashboard': typeof DashboardRoute
  '/estrategias': typeof EstrategiasRoute
  '/lstm': typeof LstmRoute
  '/mercado': typeof MercadoRoute
  '/nlp': typeof NlpRoute
  '/portafolio': typeof PortafolioRoute
  '/svm': typeof SvmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/broker': typeof BrokerRoute
  '/dashboard': typeof DashboardRoute
  '/estrategias': typeof EstrategiasRoute
  '/lstm': typeof LstmRoute
  '/mercado': typeof MercadoRoute
  '/nlp': typeof NlpRoute
  '/portafolio': typeof PortafolioRoute
  '/svm': typeof SvmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/broker': typeof BrokerRoute
  '/dashboard': typeof DashboardRoute
  '/estrategias': typeof EstrategiasRoute
  '/lstm': typeof LstmRoute
  '/mercado': typeof MercadoRoute
  '/nlp': typeof NlpRoute
  '/portafolio': typeof PortafolioRoute
  '/svm': typeof SvmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/broker'
    | '/dashboard'
    | '/estrategias'
    | '/lstm'
    | '/mercado'
    | '/nlp'
    | '/portafolio'
    | '/svm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/broker'
    | '/dashboard'
    | '/estrategias'
    | '/lstm'
    | '/mercado'
    | '/nlp'
    | '/portafolio'
    | '/svm'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/broker'
    | '/dashboard'
    | '/estrategias'
    | '/lstm'
    | '/mercado'
    | '/nlp'
    | '/portafolio'
    | '/svm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BrokerRoute: typeof BrokerRoute
  DashboardRoute: typeof DashboardRoute
  EstrategiasRoute: typeof EstrategiasRoute
  LstmRoute: typeof LstmRoute
  MercadoRoute: typeof MercadoRoute
  NlpRoute: typeof NlpRoute
  PortafolioRoute: typeof PortafolioRoute
  SvmRoute: typeof SvmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/svm': {
      id: '/svm'
      path: '/svm'
      fullPath: '/svm'
      preLoaderRoute: typeof SvmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portafolio': {
      id: '/portafolio'
      path: '/portafolio'
      fullPath: '/portafolio'
      preLoaderRoute: typeof PortafolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nlp': {
      id: '/nlp'
      path: '/nlp'
      fullPath: '/nlp'
      preLoaderRoute: typeof NlpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lstm': {
      id: '/lstm'
      path: '/lstm'
      fullPath: '/lstm'
      preLoaderRoute: typeof LstmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrategias': {
      id: '/estrategias'
      path: '/estrategias'
      fullPath: '/estrategias'
      preLoaderRoute: typeof EstrategiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broker': {
      id: '/broker'
      path: '/broker'
      fullPath: '/broker'
      preLoaderRoute: typeof BrokerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BrokerRoute: BrokerRoute,
  DashboardRoute: DashboardRoute,
  EstrategiasRoute: EstrategiasRoute,
  LstmRoute: LstmRoute,
  MercadoRoute: MercadoRoute,
  NlpRoute: NlpRoute,
  PortafolioRoute: PortafolioRoute,
  SvmRoute: SvmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
